export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_REGISTRATION = 'AUTH_REGISTRATION';

export const AUTH_INVALID_REG_INPUT = 'AUTH_INVALID_REG_INPUT';
export const AUTH_INVALID_LOG_INPUT = 'AUTH_INVALID_LOG_INPUT';

export const AUTH_REG_ERROR = 'AUTH_REG_ERROR';
export const AUTH_REG_SUCCESS = 'AUTH_REG_SUCCESS';

export const INPUTS_REG_CHANGE = 'INPUTS_REG_CHANGE';
export const INPUTS_LOG_CHANGE = 'INPUTS_LOG_CHANGE';