export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_REGISTRATION = 'AUTH_REGISTRATION';

export const AUTH_INVALID_REG_INPUT = 'AUTH_INVALID_REG_INPUT';

export const INPUTS_REG_CHANGE = 'INPUTS_REG_CHANGE';
export const INPUTS_LOG_CHANGE = 'INPUTS_LOG_CHANGE';