export const AUTH_INVALID_REG_INPUT = 'AUTH_INVALID_REG_INPUT';
export const AUTH_INVALID_LOG_INPUT = 'AUTH_INVALID_LOG_INPUT';
export const AUTH_REG_ERROR = 'AUTH_REG_ERROR';
export const AUTH_LOG_ERROR = 'AUTH_LOG_ERROR';
export const AUTH_REG_SUCCESS = 'AUTH_REG_SUCCESS';
export const AUTH_LOG_SUCCESS = 'AUTH_LOG_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const INPUTS_REG_CHANGE = 'INPUTS_REG_CHANGE';
export const INPUTS_LOG_CHANGE = 'INPUTS_LOG_CHANGE';

export const ADMIN_HEADER_CHANGE_TAB = 'ADMIN_HEADER_CHANGE_TAB';
export const ADMIN_ERROR_ALERT = 'ADMIN_ERROR_ALERT';
export const ADMIN_PRODUCTS_UPLOAD_PRODUCT_IMAGE = 'ADMIN_PRODUCTS_UPLOAD_PRODUCT_IMAGE';
export const ADMIN_PRODUCTS_REMOVE_PRODUCT_IMAGE = 'ADMIN_PRODUCTS_REMOVE_PRODUCT_IMAGE';
export const ADMIN_PRODUCTS_FORM_CHANGE = 'ADMIN_PRODUCTS_FORM_CHANGE';
export const ADMIN_PRODUCTS_FORM_DESCRIPTION_UPLOAD_IMAGES = 'ADMIN_PRODUCTS_FORM_DESCRIPTION_UPLOAD_IMAGES';
export const ADMIN_PRODUCTS_FORM_DESCRIPTION_REMOVE_IMAGES = 'ADMIN_PRODUCTS_FORM_DESCRIPTION_REMOVE_IMAGES';